core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='user')),
    path('', include('projects.urls', namespace='projects'))
]

projects/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from projects import views

app_name = 'projects'

urlpatterns = [
    path('project/<uuid:uuid>',views.ProjectView.as_view(), name='project'),
    path('project/<uuid:project_uuid>/download/<int:file_id>/', views.download_file, name='download_file'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/<str:username>', views.ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search-students/', views.UserSearchView.as_view(), name='search-students'),
    
]

projects/models.py
from django.db import models
from django.conf import settings
import uuid

class Project(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название проекта")
    description = models.TextField(verbose_name="Описание проекта", default="Описание проекта отсутствует")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_projects', verbose_name="Создан у", default=1)  # Устанавливаем дефолтного пользователя
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='led_projects', verbose_name="Лидер проекта")
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='projects', blank=True, verbose_name="Участники проекта")
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    
    def __str__(self):
        return self.title

    
    
class Application(models.Model):
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='applications')
    project_title = models.CharField(max_length=255, verbose_name="Название проекта", null=True)
    project_description = models.TextField(verbose_name="Описание проекта",null=True)
    team_members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='applications_as_member', blank=True, verbose_name="Участники команды")
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='led_applications', verbose_name="Лидер команды")
    supervisor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='supervised_applications', verbose_name="Руководитель проекта")
    applied_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи заявки")
    status = models.CharField(max_length=20, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', verbose_name="Статус")

    def __str__(self):
        return f"{self.applicant.username} -> {self.project_title}"
    
    def create_project(self):
        """
        Создает проект на основе заявки.
        """
        from projects.models import Project  # Избегаем циклического импорта
        project = Project.objects.create(
            title=self.project_title,
            description=self.project_description,
            created_by=self.supervisor,  # Проект создается преподавателем
            leader=self.leader
        )
        # Добавляем участников команды
        project.members.set(self.team_members.all())

        return project
    
class TeacherApplication(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название проекта")
    description = models.TextField(verbose_name="Описание проекта")
    requirements = models.TextField(verbose_name="Требования к команде")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_teacher_applications', verbose_name="Создан у")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    def __str__(self):
        return self.title
    
class Evaluation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='evaluations')
    grade = models.CharField(max_length=2, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('na', 'н/а')])
    team_comment = models.TextField(blank=True, null=True)
    personal_comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Оценка для проекта {self.project.title}"

tasks/models.py
from django.db import models
from django.dispatch import receiver
from projects.models import Project
from django.conf import settings
from django.utils.timezone import now
from django.db.models.signals import pre_save

class Task(models.Model):
    STATUS_CHOICES = [
        ('открыта', 'Открыта'),
        ('в работе', 'В работе'),
        ('выполнена', 'Выполнена'),
        ('требуется проверка', 'Требуется проверка'),
    ]

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=255)
    description = models.TextField()
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_tasks')
    created_at = models.DateTimeField(default=now, verbose_name="Дата создания")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='открыта')
    solution = models.TextField(blank=True, null=True)
    code_branch = models.CharField(max_length=255, blank=True, null=True)
    deadline = models.DateTimeField(verbose_name="Срок выполнения", null=True, blank=True)
    status_changed_at = models.DateTimeField(null=True, blank=True)
    marked_as_completed_at = models.DateTimeField(null=True, blank=True)
    is_necessary = models.BooleanField(verbose_name="Необходимо", default=False)    
    
    def __str__(self):
        return self.title
    
    def mark_as_completed(self):
        """Метод для установки задачи как выполненной или требующей проверки."""
        if self.status in ['выполнена', 'требуется проверка']:
            self.marked_as_completed_at = now()
            self.save()

    def check_deadline(self):
        """Метод для проверки дедлайна и установки статуса 'не в срок'."""
        if self.deadline and self.deadline < now() and self.status not in ['выполнена', 'требуется проверка']:
            self.status = 'не в срок'
            self.save()

@receiver(pre_save, sender=Task)
def update_status_fields(sender, instance, **kwargs):
    """Сигнал для обновления полей при изменении статуса."""
    if instance.pk:
        old_instance = Task.objects.get(pk=instance.pk)
        if old_instance.status != instance.status:
            instance.status_changed_at = now()
            if instance.status in ['выполнена', 'требуется проверка']:
                instance.marked_as_completed_at = now()

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.views.generic import DetailView
from django.contrib import auth, messages
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from projects.forms import ApplicationForm, TeacherApplicationForm
from projects.models import Application, Evaluation, Project, TeacherApplication
from users.forms import UserRegistrationForm
from users.models import User
from django.db import transaction

class UserLoginView(LoginView):
    template_name = 'main/index.html'
    form_class = AuthenticationForm
    
    def get_success_url(self):
        redirect_page = self.request.POST.get('next', None)
        if redirect_page:
            return redirect_page
        return reverse_lazy('users:profile', args=[self.request.user.username])
    
    def form_valid(self, form):
        user = form.get_user()
        if user:
            auth.login(self.request, user)
            messages.success(self.request, "Вы успешно вошли в систему.")
            # Перенаправляем пользователя на URL, указанный в get_success_url()
            return redirect(self.get_success_url())
        # Если пользователь не найден или сессия отсутствует, возвращаем стандартный ответ
        return super().form_valid(form)
    def form_invalid(self, form):
        # Генерируем обновленную страницу с формой, где есть ошибки
        context = self.get_context_data(login_form=form)
        html = render_to_string('main/index.html', context, request=self.request)

        # Проверяем, это AJAX-запрос или нет
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'html': html})

        # Если запрос не AJAX, перенаправляем на главную страницу
        messages.error(self.request, "Проверьте корректность данных в форме.")
        return redirect('main:index')

class UserRegistrationView(CreateView):
    template_name = 'main/index.html'
    form_class = UserRegistrationForm

    def get_success_url(self):
        # После успешной регистрации перенаправляем на профиль пользователя
        return reverse_lazy('users:profile', args=[self.request.user.username])

    def form_valid(self, form):
        user = form.save()  # Сохраняем форму и создаем пользователя
        if user.is_teacher == True:
            user.is_student = False
            user.save()
        
        auth.login(self.request, user)  # Выполняем авторизацию для нового пользователя
        messages.success(self.request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт.")

        # Проверяем, это ли AJAX-запрос
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return self.render_messages()

        # Перенаправляем пользователя, если запрос не AJAX
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        # Генерируем обновленную страницу с формой, где есть ошибки
        context = self.get_context_data(register_form=form, login_form=AuthenticationForm())
        html = render_to_string('main/index.html', context, request=self.request)

        # Проверяем, это AJAX-запрос или нет
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'html': html})

        # Если запрос не AJAX, перенаправляем на главную страницу
        messages.error(self.request, f"Проверьте корректность данных в форме.")
        return render(self.request, 'main/index.html', context)


    def render_messages(self):
        """Рендеринг только блока сообщений."""
        html = render_to_string('messages.html', {'messages': messages.get_messages(self.request)})
        return JsonResponse({'html': html})
    
class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'users/profile.html'
    context_object_name = 'user'

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        # Передаем заявки и форму для подачи заявки в контекст
        if user.is_teacher:
            context['teacher_applications'] = TeacherApplication.objects.filter(created_by=user)
            context['teacher_application_form'] = TeacherApplicationForm()
            
            # Если пользователь - преподаватель, показываем заявки, адресованные ему
            context['applications'] = Application.objects.filter(supervisor=user, status='pending')
        else:
            # Если пользователь - студент, показываем его заявки и учителя
            context['teacher_applications'] = TeacherApplication.objects.all()
            context['applications'] = Application.objects.filter(applicant=user)
        context['application_form'] = ApplicationForm()
        if user.is_teacher:
            projects = Project.objects.filter(created_by=user)
        else:
            projects = Project.objects.filter(members=user)    
        context['projects'] = projects
        
        evaluations = Evaluation.objects.filter(project__in=projects)
        context['evaluations'] = evaluations
        
        return context
    
    def post(self, request, *args, **kwargs):
        if 'submit_application' in request.POST:
            form = ApplicationForm(request.POST)
            if form.is_valid():
                application = form.save(commit=False)
                application.applicant = request.user
                
                # Получаем данные из js
                leader_username = request.POST.get('leader_input')
                team_members_usernames = request.POST.getlist('team_members_input')
                
                # Находим лидера и участников команды
                leader = User.objects.filter(username=leader_username).first()
                team_members = User.objects.filter(username__in=team_members_usernames)
                application.leader = leader
                
                application.save()
                application.team_members.set(team_members)  # Сохраняем участников команды
                
                messages.success(request, 'Заявка успешно отправлена.')
            else:
                messages.error(request, 'Ошибка при отправке заявки.')
            return redirect('users:profile', username=request.user.username)
        
        # Обработка принятия заявки преподавателем
        elif 'approve_application' in request.POST:
            application_id = request.POST.get('application_id')
            application = get_object_or_404(Application, id=application_id)
            
            if application.supervisor != request.user:
                messages.error(request, 'У вас нет прав на выполнение этого действия.')
                return redirect('users:profile', username=self.request.user.username)

            application.status = "approved"
            # Проверяем, что заявка одобрена
            if application.status == 'approved':
                with transaction.atomic():
                    # Создаем проект
                    project = application.create_project()

                    # Удаляем заявку
                    application.delete()
            messages.success(request, f"Заявка принята. Проект '{project.title}' создан.")
            return redirect('users:profile', username=self.request.user.username)
        elif 'create_application' in request.POST:
            form = TeacherApplicationForm(request.POST)
            if form.is_valid():
                application = form.save(commit=False)
                application.created_by = request.user
                application.save()
                messages.success(request, 'Заявка успешно создана.')
            else:
                messages.error(request, 'Ошибка при создании заявки.')
            return redirect('users:profile', username=request.user.username)
        
        elif 'apply_for_application' in request.POST:
            application_id = request.POST.get('application_id')
            teacher_application = get_object_or_404(TeacherApplication, id=application_id)

            # Получаем данные из формы
            leader_username = request.POST.get('leader_input')
            team_members_usernames = request.POST.getlist('team_members_input')
            
            # Проверяем, указан ли лидер
            if not leader_username:
                messages.error(request, 'Пожалуйста, укажите лидера команды.')
                return redirect('users:profile', username=request.user.username)

            # Проверяем, указаны ли участники
            if not team_members_usernames:
                messages.error(request, 'Пожалуйста, добавьте хотя бы одного участника команды.')
                return redirect('users:profile', username=request.user.username)
            print(request.POST)

            # Находим лидера и участников команды
            leader = User.objects.filter(username=leader_username).first()
            team_members = User.objects.filter(username__in=team_members_usernames)
            print(team_members)
            if not team_members.exists():
                messages.error(request, 'Не удалось найти участников команды.')
                return redirect('users:profile', username=request.user.username)
            
            # Создаем заявку
            student_application = Application.objects.create(
                applicant=request.user,
                project_title=teacher_application.title,
                project_description=teacher_application.description,
                supervisor=teacher_application.created_by,
                leader=leader

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Базовая страница</title>
        <link rel="stylesheet" href="{% static 'deps/css/home.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    </head>
{% endblock %}

{% block header %}
    <!-- Шапка -->
    <header class="header">
        <a href="{% url 'users:profile' user.username %}" class="logo">
            <img src="{% static 'deps/logo.jpg' %}" alt="logo" class="avatar-img">
            <span class="home">Home</span>

        </a>
        <div class="user-info">
        <span class="username">{{ user.username }}</span>
        <div class="avatar" onclick="toggleDropdown()">
            <img src="{% static 'deps/logo.jpg' %}" alt="Avatar" class="avatar-img">
            <ul id="avatar-dropdown" class="dropdown">
                <li><a href="#">Настройки</a></li>
                <li><a href="{% url 'users:logout' %}">Выход</a></li>
            </ul>
        </div>
    </header>
{%endblock%}

{% block content %}
<!-- Основной блок -->
    <main class="main-content">
        <!-- Навигационная панель -->
        <nav class="navigation">
            <div class="navigation-item" onclick="showSection('my-projects')">Мои проекты</div> 
            {% if user.is_student %}
                <div class="navigation-item" onclick="showSection('submit-application')">Подать заявку на проект</div> 
            {% else %}
                <div class="navigation-item" onclick="showSection('create-project')">Создать проект</div> 
            {% endif %} 
            <div class="navigation-item" onclick="showSection('view-applications')">Просмотр заявок</div> 
            <div class="navigation-item" onclick="showSection('my-applications')">Мои заявки</div> 
        </nav>
    <section class="content" id="content">
      <!-- Мои проекты -->
      <div id="my-projects" class="section">
        <h1>Мои проекты</h1>
        {% for project in projects %}
            <div class="application-block">
                <div class="project-container">
                    <div class="project-info">
                        <h2>{{ project.title }}</h2>
                        <p>{{ project.description }}</p>
                        <p><strong>Лидер:</strong> <span class="nickname leader"> {{ project.leader.username }}</span></p>
                        <p><strong>Участники:</strong>
                            {% for member in project.members.all %}
                                <span class="nickname"> {{ member.username }} </span>
                            {% endfor %}
                        </p>
                    </div>
                    <div class="project-evaluation">
                        {% for evaluation in evaluations %}
                            {% if evaluation.project == project %}
                                <p>Оценка: {{ evaluation.get_grade_display }}</p>
                                <p>Комментарий команде: {{ evaluation.team_comment }}</p>
                                {% if user.is_teacher and user == project.created_by%}
                                    <p>Личный комментарий: {{ evaluation.personal_comment }}</p>
                                {%endif%}
                            {% endif %}
                        {% empty %}
                            <p>Оценка отсутствует.</p>
                        {% endfor %}
                    </div>
                </div>
                
                <form action="{% url 'projects:project' uuid=project.uuid %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Перейти к проекту</button>
                </form>
            </div>
        {% empty %}
            <div class="application-block">Нет доступных проектов.</div>
        {% endfor %}
      </div>

      <!-- Подать заявку на проект -->
      <div id="submit-application" class="section" style="display: none;">
        <h1>Подать заявку на проект</h1>
        <form method="post" action="{% url 'users:profile' user.username %}">
            {% csrf_token %}
            {% for field in application_form %}
            <div class="form-group">
                {{field.label_tag}}
                <div>{{field}}</div>
            </div>
            {% endfor %}
             <!-- Контейнер для добавления участников -->
            <div id="team-members-container-application" class="team-members-container">
                <label>Участники команды:</label>
                <div class="form-group">
                    <input type="text" class="team-member-autocomplete" name="team_members_input" placeholder="Введите username">
                    <button type="button" class="confirm-member">Подтвердить</button>
                </div>
                {% include 'partials/dropdown.html' %}
                <ul id="team-members-list" class="team-members-list"></ul>
                
            </div>
            <!-- Поле для ввода лидера -->
            <div class="form-group">
                <label for="leader">Лидер команды:</label>
                <div>
                    <select name="leader_input" id="leader-select-application">
                        <option value="">Выберите лидера</option>
                    </select>
                </div>
            </div>
            <button type="submit" name="submit_application">Отправить заявку</button>
        </form>
      </div>
      {% if user.is_teacher %}
        <div id="create-project" class="section" style="display: none;">
            <h1>Создать проект</h1>
            <form method="post" action="{% url 'users:profile' user.username %}">
                {% csrf_token %}
                {% for field in teacher_application_form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    <div>{{ field }}</div>
                </div>
                {% endfor %}
                <button type="submit" name="create_application">Создать заявку</button>
            </form>
        </div>
      {% endif %}
      <!-- Просмотр заявок -->
      <div id="view-applications" class="section" style="display: none;">
        <h1>Просмотр заявок</h1>
        {% if user.is_teacher %}
        
            {% for application in applications %}
                <div class="application-block">
                    <h2>{{ application.project_title }}</h2>
                    <p><strong>Описание:</strong> {{ application.project_description }}</p>
                    <p><strong>Лидер:</strong> {{ application.leader.username }}</p>
                    <p><strong>Участники:</strong>
                        <ul>
                            {% for member in application.team_members.all %}
                                <li>{{ member.username }}</li>
                            {% endfor %}
                        </ul>
                    </p>
                    {% if user.is_teacher %}
                        <form method="post" action="{% url 'users:profile' username=user.username %}">
                            {% csrf_token %}
                            <input type="hidden" name="application_id" value="{{ application.id }}">
                            <button type="submit" name="approve_application">Принять заявку</button>
                        </form>
                    {% endif %}
                </div>
            {% empty %}
                <div class="application-block">Нет новых заявок.</div>
            {% endfor %}
        {% else %}
            {% for application in teacher_applications %}
                <div class="application-block">
                    <h2>{{ application.title }}</h2>
                    <p><strong>Описание:</strong> {{ application.description }}</p>
                    <p><strong>Требования:</strong> {{ application.requirements }}</p>
                    <form method="post" action="{% url 'users:profile' username=user.username %}">
                        {% csrf_token %}
                        <input type="hidden" name="application_id" value="{{ application.id }}">

                        <!-- Контейнер для добавления участников -->
                        <div id="team-members-container-{{ application.id }}" class="team-members-container">
                            <label>Участники команды:</label>
                            <div class="form-group">
                                <input type="text" class="team-member-autocomplete" name="team_members_input" placeholder="Введите username">
                                <button type="button" class="confirm-member">Подтвердить</button>
                            </div>
                            {% include 'partials/dropdown.html' %}
                            <ul id="team-members-list" class="team-members-list"></ul>
                            
                        </div>
                        <!-- Поле для ввода лидера -->
                        <div class="form-group">
                            <label for="leader">Лидер команды:</label>
                            <div>
                                <select name="leader_input" id="leader-select-{{ application.id }}">
                                    <option value="">Выберите лидера</option>
                                </select>
                            </div>
                        </div>
                        
                        <button type="submit" name="apply_for_application">Подать заявку</button>
                    </form>
                </div>
            {% empty %}
                <div class="application-block">Нет доступных заявок.</div>
            {% endfor %}
        {% endif %}
      </div>
        
      <!-- Мои заявки -->
      <div id="my-applications" class="section" style="display: none;">
        <h1>Мои заявки</h1>
        {% if user.is_teacher %}
            {% for application in teacher_applications %}
                <div class="application-block">
                    <h2>{{ application.title }}</h2>
                    <form method="post" action="{% url 'users:profile' username=user.username %}">
                        {% csrf_token %}
                        <input type="hidden" name="application_id" value="{{ application.id }}">
                        <button type="submit" name="delete_application">Удалить заявку</button>
                    </form>
                </div>
            {% empty %}
                <div class="application-block">Нет заявок.</div>
            {% endfor %}
        {% else %}
            {% for application in applications %}
                <div class="application-block">
                    <h2>{{ application.project_title }}</h2>
                    <div class="status">Статус: <span class="status-text">{{ application.get_status_display }}</span></div>
                    <form method="post" action="{% url 'users:profile' username=user.username %}">
                        {% csrf_token %}
                        <input type="hidden" name="application_id" value="{{ application.id }}">
                        <button type="submit" name="delete_application">Удалить заявку</button>
                    </form>
                </div>
            {% empty %}
                <div class="application-block">Нет заявок.</div>
            {% endfor %}
        {% endif %}
      </div>
    </section>
    </main>
<script src="{% static 'deps/js/add_teammate.js' %}"></script>
<script src="{% static 'deps/js/profile.js' %}"></script>
<script>
    function toggleDropdown() {
            const dropdown = document.getElementById('avatar-dropdown');
            dropdown.classList.toggle('show');
        }
</script>
{% endblock %}