core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='user')),
    path('', include('projects.urls', namespace='projects'))
]

main/urls.py
from django.urls import path
from .views import AboutView, IndexView, NewsView

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Например, главная страница
    path('news/', NewsView.as_view(), name= 'news'),
    path('about/', AboutView.as_view(), name= 'about'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/<str:username>', views.ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search-students/', views.UserSearchView.as_view(), name='search-students'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
{% block head %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Система Управления Проектами{%endblock%}</title> 
        {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> {% endcomment %}
        <link rel="stylesheet" href="{% static 'deps/css/index.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    </head>     
{% endblock %}
<body>
    
    {% block header %}
    <header class="header">
        
        <a href="{% url 'main:index' %}" class="logo">
            <img src="{% static 'deps/logo.jpg' %}" alt="Логотип">
        </a>
        <nav>
            <a href="{% url 'main:news' %}" class="nav-item">Новости</a>
            <a href="{% url 'main:about' %}" class="nav-item">О проекте</a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}" class="nav-item">Выйти</a>
            {% else %}
                
            {% endif %}
        </nav>
        
    </header>
    {% endblock %}
    <div class="notifications-section">
        <!-- Вставляем уведомления -->
        {% include 'partials/notifications.html' %}
    </div>
    {% block content %}
    
    {% endblock %}

    {% block footer %}
    <footer>
        <div class="contact">
            <p>Екатерина Чумакова</p>
            <a href="mailto:ekkaterina_chumakova@mail.ru"><i class="fas fa-envelope"></i></a>
            <a href="tel:+79210773516"><i class="fas fa-phone"></i></a>
            <a href="https://t.me/Blblllblbll"><i class="fab fa-telegram-plane"></i></a>
            <a href="https://m.vk.com/miliosss"><i class="fab fa-vk"></i></a><br>
        </div>
        <div class="contact">
            <p>Даниил Суббота</p>
            <a href="mailto:daniil.maslike@yandex.ru"><i class="fas fa-envelope"></i></a>
            <a href="tel:+79118428356"><i class="fas fa-phone"></i></a>
            <a href="https://t.me/Maslike"><i class="fab fa-telegram-plane"></i></a>
            <a href="https://m.vk.com/maslike"><i class="fab fa-vk"></i></a>
        </div>
    </footer>
    {% endblock %}
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'deps/js/notifications.js' %}"></script>
</body>
</html>