core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='user')),
    path('', include('projects.urls', namespace='projects'))
]

main/urls.py
from django.urls import path
from .views import AboutView, IndexView, NewsView

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Например, главная страница
    path('news/', NewsView.as_view(), name= 'news'),
    path('about/', AboutView.as_view(), name= 'about'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/<str:username>', views.ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search-students/', views.UserSearchView.as_view(), name='search-students'),
    
]

main/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.forms import AuthenticationForm
from users.forms import UserRegistrationForm


class IndexView(TemplateView):
    template_name = 'main/index.html'
    def dispatch(self, request, *args, **kwargs):
        # Проверка, авторизован ли пользователь
        if request.user.is_authenticated:
            # Перенаправление авторизованного пользователя на страницу профиля
            return redirect(reverse_lazy('users:profile', args=[self.request.user.username]))
        # Если пользователь не авторизован, продолжаем обычный процесс
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        context['login_form'] = AuthenticationForm()
        context['register_form'] = UserRegistrationForm()
        return context
    
class NewsView(TemplateView):
    template_name = 'main/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости'
        return context

class AboutView(TemplateView):
    template_name = 'main/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'О проекте'
        return context
    

main/templates/main/about.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>О проекте</title>
    <link rel="stylesheet" href="{% static 'deps/css/index.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
{% endblock %}
    {% block content %}
    <!-- Основная часть -->
    <main>
        <h1>Здесь будет информация о проекте</h1>
    </main>
    {% endblock %}
    

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    {% if not user.is_authenticated %}
        <!-- Основная часть -->
        <main>
            <h1>ДОБРО ПОЖАЛОВАТЬ В СИСТЕМУ УПРАВЛЕНИЯ ПРОЕКТАМИ</h1>
            <div class="buttons">
                <button class="role-button" id="reg-button" >Регистрация</button>
                <button class="role-button" id="entry-button">Вход</button>
            </div>
        </main>

        <!-- Модальные окна -->
        <div id="modal-entry" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Авторизация</h5>
                    <button type="button" class="btn-close" onclick="closeModal('modal-entry')">&times;</button>
                </div>
                <form action="{% url 'users:login'  %}" method="post">
                    {% csrf_token %}
                    {{ login_form.as_p }}
                    <button class="button" type="submit">Войти</button>
                </form>
            </div>
        </div>
        <div id="modal-reg" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Регистрация</h5>
                    <button type="button" class="btn-close" onclick="closeModal('modal-reg')">&times;</button>
                </div>
                <div id="form-container">
                    {% include "partials/modal_registration.html" %}
                </div>
            </div>
        </div>
        <script src="{% static 'deps/js/index.js' %}"></script>
    {% else %}
    <div class="buttons">
        <a href="{% url 'users:logout' %}">
            <button>Выйти</button>
        </a>
    </div>
    {% endif %}
{% endblock %}

main/templates/main/news.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Новости</title>
        <link rel="stylesheet" href="{% static 'deps/css/news.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    </head>
{% endblock %}
<body>
    {% block content %}
    <main>
        <div class="content-container">
            <!-- Список новостей -->
            <div class="news-list">
                <h2>Новости</h2>
                <ul>
                    <li class="news-item">Новость 1</li>
                    <li class="news-item">Новость 2</li>
                    <li class="news-item">Новость 3</li>
                </ul>
            </div>

            <!-- Детали выбранной новости -->
            <div class="news-details">
                <h2 id="news-title">Новость 1</h2>
                <p id="news-text">Текст новости 1. Здесь будет описание первой новости.</p>
            </div>

            <!-- Объявления -->
            <div class="announcements">
                <h2>Объявления</h2>
                <div class="slider">
                    <div class="announcement"><img src="1.jpg" alt="Объявление 1"></div>
                    <div class="announcement"><img src="2.jpg" alt="Объявление 2"></div>
                    <div class="announcement"><img src="3.jpg" alt="Объявление 3"></div>
                </div>
                <div class="slider-controls">
                    <span class="slider-btn active"></span>
                    <span class="slider-btn"></span>
                    <span class="slider-btn"></span>
                </div>
            </div>
        </div>
    </main>


    <script src="{% static 'deps/js/news.js' %}"></script>
    {% endblock %}
</body>
</html>